#!/bin/bash

touch host_services.txt

if [ -f host_services.txt ]; then

    trap "{ rm -f host_services.txt; exit 255; }" EXIT
fi

scan_type="$1"
HOST="$2"
COUNT="$3"

if [ "$scan_type" == "" ] || [ "$HOST" == "" ] || [ "$COUNT" == "" ]; then

   echo -e "
USAGE EXAMPLE:
#----------------------------------------------------------#
pscan t 192.168.1.1 500 <-- for TCP

(or...)

pscan u 192.168.1.1 500 <-- for UDP\n"

   exit 1
fi

function P_SCAN() {

tcp_scan() {

for port in $(seq 1 $COUNT); do

    nc -v -z -w1 $HOST $port >> host_services.txt 2>&1 && wait
    cat host_services.txt | grep -e 'Connection to' | sed -e 's/ succeeded!//g' -e 's/Connection to //g' -e "s/$HOST //g" && wait
    rm host_services.txt

done
}

udp_scan() {

for port in $(seq 1 $COUNT); do

    nc -v -z -u -w1 $HOST $port >> host_services.txt 2>&1 && wait
    cat host_services.txt | grep -e 'Connection to' | sed -e 's/ succeeded!//g' -e 's/Connection to //g' -e "s/$HOST //g" && wait
    rm host_services.txt

done
}

if [ "$scan_type" == "u" ]; then
   udp_scan
elif [ "$scan_type" == "t" ]; then
   tcp_scan
fi

}

P_SCAN
